### ISSUE TITLE
FM.PRG out of date

### ISSUE THREAD

**Issue by tomxp411** [cx16forum/sdcard#1]
unartic99653 — Today at 6:39 PM
@The 8-Bit Guy Hi David, I noticed an old version of FM.PRG is on the current image. The current version is on the forum. As it has lots of improvements, it would be good for quality to replace it 🙂  https://cx16forum.com/forum/viewtopic.php?t=7014

**Comment by JimmyDansbo** [comment]
Updated FM.PRG to version 1.2 with https://github.com/cx16forum/sdcard/commit/0662a7c241410c6409095eb83698f23e7a8b3286
