### ISSUE TITLE
update CX16ASSEMBLER

### ISSUE THREAD

**Issue by irmen** [cx16forum/sdcard#5]
DEV/CX16ASSEMBLER should be updated , the latest version fixed a bug with .include directives.

https://cx16forum.com/forum/viewtopic.php?t=6294

The README file should probably also mention the source code repository ( https://github.com/irmen/cx16assem) , or the forum post above.

(Not sure why the prg on the sdcard is called CX16ASSEMBLER.PRG...)

**Comment by JimmyDansbo** [comment]
Assembler has been updated on SDcard through https://github.com/cx16forum/sdcard/commit/6a94578e2137aae697eaeb314991cda8a5fc9019
