### ISSUE TITLE
Update GAMES-TEXT

### ISSUE THREAD

**Issue by tomxp411** [cx16forum/sdcard#6]
Latest from David, with fixes for R47
> Can you replace the entire GAMES-TEXT folder with this?  All of these games were broken with R47 but have been fixed now.

[GAMES-TEXT.ZIP](https://github.com/cx16forum/sdcard/files/15045918/GAMES-TEXT.ZIP)

Since he has tested them, we just need to insert them into the correct place and update the repo.

**Comment by JimmyDansbo** [comment]
I replaced all the games on my local copy of the SDcard, but none of them work.
Games just hang after the startup screen and emulator warns that they are using different Rockwell instructions.
I have also tried it on real hardware which acts the same as well as blinking the activity LED, indicating that some file is not found.

**Comment by tomxp411** [comment]
The good news is, these all look like Ozmoo games. I should be able to pull down a clean set from the Ozmoo web site.

**Comment by JimmyDansbo** [comment]
GAMES-TEXT have now been updated. Now the ZCODE is named [ZCODE]. I thought it should be renamed back to ZCODE, but then it does not work. https://github.com/cx16forum/sdcard/commit/375b9b393726b66369eafef4fbc6806f02d18ada
